export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";

export const CART_CREATE_REQUEST = "CART_CREATE_REQUEST";
export const CART_CREATE_SUCCESS = "CART_CREATE_SUCCESS";
export const CART_CREATE_FAIL = "CART_CREATE_FAIL";

export const CART_INCREMENT_REQUEST = "CART_INCREMENT_REQUEST";
export const CART_INCREMENT_SUCCESS = "CART_INCREMENT_SUCCESS";
export const CART_INCREMENT_FAIL = "CART_INCREMENT_FAIL";

export const CART_DECREMENT_REQUEST = "CART_DECREMENT_REQUEST";
export const CART_DECREMENT_SUCCESS = "CART_DECREMENT_SUCCESS";
export const CART_DECREMENT_FAIL = "CART_DECREMENT_FAIL";

export const CART_DELETE_REQUEST = "CART_DELETE_REQUEST";
export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS";
export const CART_DELETE_FAIL = "CART_DELETE_FAIL";